sudo: required  
dist: trusty
language: node_js
node_js:
  - "8"
addons:
  chrome: stable

cache:
  directories:
  - node_modules

install:
  - npm install
  
script:
  - npm test
  - npm run e2e
  - npm run test:coverage

after_success:
  - npm run deploy