sudo: required  
dist: trusty
language: node_js
node_js:
  - "8"
addons:
  chrome: stable

cache:
  directories:
  - node_modules

install:
  - npm install

jobs:
  include:
    - stage: unit-test
    script:
      - npm test
      - npm run test:coverage
    - stage: e2e-test
    script:
      - npm run e2e
    - stage: deploy
    script: npm run deploy
