sudo: required
dist: trusty
language: node_js
node_js:
  - "8"

cache:
  bundler: true
  directories:
    - node_modules

install:
  - npm install

script:
  - npm test
  - npm run e2e
  - npm run test:coverage

jobs:
  include:
    - stage: Tests
      script: npm test
        npm run test:coverage
    - stage: Tests
      script: npm run e2e
    - stage: deploy
      script: npm run deploy
