sudo: required  
dist: trusty
language: node_js
node_js:
  - "8"
addons:
  chrome: stable

cache:
  bundler
  directories:
  - node_modules

install:
  - npm install

jobs:
  include:
    - stage: Tests
      script:
        npm test
        npm run test:coverage
    - stage: Tests
      script:
        npm run e2e
    - stage: deploy
      script: 
        npm run deploy
