language: node_js

addons:
  chrome: stable

node_js:
  - "7"

before_install:
  - npm i -g npm
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install
  
script:
  - npm test
  - npm run e2e
  - npm run test:coverage
  - npm run deploy