language: node_js

addons:
  chrome: stable

node_js:
  - "7"

before_install:
  - npm i -g npm
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install:
  - npm install
  
script:
  - npm test
  - npm run e2e
  - npm run test:coverage
  - npm run deploy