sudo: required  
dist: trusty
language: node_js
node_js:
  - "7"
addons:
  chrome: stable



before_install:
  - npm i -g npm
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install
  
script:
  - npm test
  - npm run e2e
  - npm run test:coverage
  - npm run deploy